//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPWebServices2.Calculator2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Calculator2.CalculateSoap")]
    public interface CalculateSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SOAPWebServices2.Calculator2.HelloWorldResponse HelloWorld(SOAPWebServices2.Calculator2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPWebServices2.Calculator2.HelloWorldResponse> HelloWorldAsync(SOAPWebServices2.Calculator2.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name operation from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calculation", ReplyAction="*")]
        SOAPWebServices2.Calculator2.CalculationResponse Calculation(SOAPWebServices2.Calculator2.CalculationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calculation", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPWebServices2.Calculator2.CalculationResponse> CalculationAsync(SOAPWebServices2.Calculator2.CalculationRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayGoodBye", ReplyAction="*")]
        SOAPWebServices2.Calculator2.SayGoodByeResponse SayGoodBye(SOAPWebServices2.Calculator2.SayGoodByeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayGoodBye", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPWebServices2.Calculator2.SayGoodByeResponse> SayGoodByeAsync(SOAPWebServices2.Calculator2.SayGoodByeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SOAPWebServices2.Calculator2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SOAPWebServices2.Calculator2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPWebServices2.Calculator2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SOAPWebServices2.Calculator2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Calculation", Namespace="http://tempuri.org/", Order=0)]
        public SOAPWebServices2.Calculator2.CalculationRequestBody Body;
        
        public CalculationRequest() {
        }
        
        public CalculationRequest(SOAPWebServices2.Calculator2.CalculationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double x;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double y;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operation;
        
        public CalculationRequestBody() {
        }
        
        public CalculationRequestBody(double x, double y, string operation) {
            this.x = x;
            this.y = y;
            this.operation = operation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPWebServices2.Calculator2.CalculationResponseBody Body;
        
        public CalculationResponse() {
        }
        
        public CalculationResponse(SOAPWebServices2.Calculator2.CalculationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalculationResult;
        
        public CalculationResponseBody() {
        }
        
        public CalculationResponseBody(double CalculationResult) {
            this.CalculationResult = CalculationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayGoodByeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayGoodBye", Namespace="http://tempuri.org/", Order=0)]
        public SOAPWebServices2.Calculator2.SayGoodByeRequestBody Body;
        
        public SayGoodByeRequest() {
        }
        
        public SayGoodByeRequest(SOAPWebServices2.Calculator2.SayGoodByeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayGoodByeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public SayGoodByeRequestBody() {
        }
        
        public SayGoodByeRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayGoodByeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayGoodByeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPWebServices2.Calculator2.SayGoodByeResponseBody Body;
        
        public SayGoodByeResponse() {
        }
        
        public SayGoodByeResponse(SOAPWebServices2.Calculator2.SayGoodByeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayGoodByeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SayGoodByeResult;
        
        public SayGoodByeResponseBody() {
        }
        
        public SayGoodByeResponseBody(string SayGoodByeResult) {
            this.SayGoodByeResult = SayGoodByeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculateSoapChannel : SOAPWebServices2.Calculator2.CalculateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculateSoapClient : System.ServiceModel.ClientBase<SOAPWebServices2.Calculator2.CalculateSoap>, SOAPWebServices2.Calculator2.CalculateSoap {
        
        public CalculateSoapClient() {
        }
        
        public CalculateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPWebServices2.Calculator2.HelloWorldResponse SOAPWebServices2.Calculator2.CalculateSoap.HelloWorld(SOAPWebServices2.Calculator2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SOAPWebServices2.Calculator2.HelloWorldRequest inValue = new SOAPWebServices2.Calculator2.HelloWorldRequest();
            inValue.Body = new SOAPWebServices2.Calculator2.HelloWorldRequestBody();
            SOAPWebServices2.Calculator2.HelloWorldResponse retVal = ((SOAPWebServices2.Calculator2.CalculateSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPWebServices2.Calculator2.HelloWorldResponse> SOAPWebServices2.Calculator2.CalculateSoap.HelloWorldAsync(SOAPWebServices2.Calculator2.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPWebServices2.Calculator2.HelloWorldResponse> HelloWorldAsync() {
            SOAPWebServices2.Calculator2.HelloWorldRequest inValue = new SOAPWebServices2.Calculator2.HelloWorldRequest();
            inValue.Body = new SOAPWebServices2.Calculator2.HelloWorldRequestBody();
            return ((SOAPWebServices2.Calculator2.CalculateSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPWebServices2.Calculator2.CalculationResponse SOAPWebServices2.Calculator2.CalculateSoap.Calculation(SOAPWebServices2.Calculator2.CalculationRequest request) {
            return base.Channel.Calculation(request);
        }
        
        public double Calculation(double x, double y, string operation) {
            SOAPWebServices2.Calculator2.CalculationRequest inValue = new SOAPWebServices2.Calculator2.CalculationRequest();
            inValue.Body = new SOAPWebServices2.Calculator2.CalculationRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            inValue.Body.operation = operation;
            SOAPWebServices2.Calculator2.CalculationResponse retVal = ((SOAPWebServices2.Calculator2.CalculateSoap)(this)).Calculation(inValue);
            return retVal.Body.CalculationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPWebServices2.Calculator2.CalculationResponse> SOAPWebServices2.Calculator2.CalculateSoap.CalculationAsync(SOAPWebServices2.Calculator2.CalculationRequest request) {
            return base.Channel.CalculationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPWebServices2.Calculator2.CalculationResponse> CalculationAsync(double x, double y, string operation) {
            SOAPWebServices2.Calculator2.CalculationRequest inValue = new SOAPWebServices2.Calculator2.CalculationRequest();
            inValue.Body = new SOAPWebServices2.Calculator2.CalculationRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            inValue.Body.operation = operation;
            return ((SOAPWebServices2.Calculator2.CalculateSoap)(this)).CalculationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPWebServices2.Calculator2.SayGoodByeResponse SOAPWebServices2.Calculator2.CalculateSoap.SayGoodBye(SOAPWebServices2.Calculator2.SayGoodByeRequest request) {
            return base.Channel.SayGoodBye(request);
        }
        
        public string SayGoodBye(string name) {
            SOAPWebServices2.Calculator2.SayGoodByeRequest inValue = new SOAPWebServices2.Calculator2.SayGoodByeRequest();
            inValue.Body = new SOAPWebServices2.Calculator2.SayGoodByeRequestBody();
            inValue.Body.name = name;
            SOAPWebServices2.Calculator2.SayGoodByeResponse retVal = ((SOAPWebServices2.Calculator2.CalculateSoap)(this)).SayGoodBye(inValue);
            return retVal.Body.SayGoodByeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPWebServices2.Calculator2.SayGoodByeResponse> SOAPWebServices2.Calculator2.CalculateSoap.SayGoodByeAsync(SOAPWebServices2.Calculator2.SayGoodByeRequest request) {
            return base.Channel.SayGoodByeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPWebServices2.Calculator2.SayGoodByeResponse> SayGoodByeAsync(string name) {
            SOAPWebServices2.Calculator2.SayGoodByeRequest inValue = new SOAPWebServices2.Calculator2.SayGoodByeRequest();
            inValue.Body = new SOAPWebServices2.Calculator2.SayGoodByeRequestBody();
            inValue.Body.name = name;
            return ((SOAPWebServices2.Calculator2.CalculateSoap)(this)).SayGoodByeAsync(inValue);
        }
    }
}
