//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPClient.CalculatorWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorWebService.CalculateSoap")]
    public interface CalculateSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SOAPClient.CalculatorWebService.HelloWorldResponse HelloWorld(SOAPClient.CalculatorWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPClient.CalculatorWebService.HelloWorldResponse> HelloWorldAsync(SOAPClient.CalculatorWebService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name operation from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calculation", ReplyAction="*")]
        SOAPClient.CalculatorWebService.CalculationResponse Calculation(SOAPClient.CalculatorWebService.CalculationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calculation", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPClient.CalculatorWebService.CalculationResponse> CalculationAsync(SOAPClient.CalculatorWebService.CalculationRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayGoodBye", ReplyAction="*")]
        SOAPClient.CalculatorWebService.SayGoodByeResponse SayGoodBye(SOAPClient.CalculatorWebService.SayGoodByeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayGoodBye", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPClient.CalculatorWebService.SayGoodByeResponse> SayGoodByeAsync(SOAPClient.CalculatorWebService.SayGoodByeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SOAPClient.CalculatorWebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SOAPClient.CalculatorWebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPClient.CalculatorWebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SOAPClient.CalculatorWebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Calculation", Namespace="http://tempuri.org/", Order=0)]
        public SOAPClient.CalculatorWebService.CalculationRequestBody Body;
        
        public CalculationRequest() {
        }
        
        public CalculationRequest(SOAPClient.CalculatorWebService.CalculationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double x;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double y;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operation;
        
        public CalculationRequestBody() {
        }
        
        public CalculationRequestBody(double x, double y, string operation) {
            this.x = x;
            this.y = y;
            this.operation = operation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPClient.CalculatorWebService.CalculationResponseBody Body;
        
        public CalculationResponse() {
        }
        
        public CalculationResponse(SOAPClient.CalculatorWebService.CalculationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalculationResult;
        
        public CalculationResponseBody() {
        }
        
        public CalculationResponseBody(double CalculationResult) {
            this.CalculationResult = CalculationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayGoodByeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayGoodBye", Namespace="http://tempuri.org/", Order=0)]
        public SOAPClient.CalculatorWebService.SayGoodByeRequestBody Body;
        
        public SayGoodByeRequest() {
        }
        
        public SayGoodByeRequest(SOAPClient.CalculatorWebService.SayGoodByeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayGoodByeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public SayGoodByeRequestBody() {
        }
        
        public SayGoodByeRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayGoodByeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayGoodByeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPClient.CalculatorWebService.SayGoodByeResponseBody Body;
        
        public SayGoodByeResponse() {
        }
        
        public SayGoodByeResponse(SOAPClient.CalculatorWebService.SayGoodByeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayGoodByeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SayGoodByeResult;
        
        public SayGoodByeResponseBody() {
        }
        
        public SayGoodByeResponseBody(string SayGoodByeResult) {
            this.SayGoodByeResult = SayGoodByeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculateSoapChannel : SOAPClient.CalculatorWebService.CalculateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculateSoapClient : System.ServiceModel.ClientBase<SOAPClient.CalculatorWebService.CalculateSoap>, SOAPClient.CalculatorWebService.CalculateSoap {
        
        public CalculateSoapClient() {
        }
        
        public CalculateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPClient.CalculatorWebService.HelloWorldResponse SOAPClient.CalculatorWebService.CalculateSoap.HelloWorld(SOAPClient.CalculatorWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SOAPClient.CalculatorWebService.HelloWorldRequest inValue = new SOAPClient.CalculatorWebService.HelloWorldRequest();
            inValue.Body = new SOAPClient.CalculatorWebService.HelloWorldRequestBody();
            SOAPClient.CalculatorWebService.HelloWorldResponse retVal = ((SOAPClient.CalculatorWebService.CalculateSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPClient.CalculatorWebService.HelloWorldResponse> SOAPClient.CalculatorWebService.CalculateSoap.HelloWorldAsync(SOAPClient.CalculatorWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPClient.CalculatorWebService.HelloWorldResponse> HelloWorldAsync() {
            SOAPClient.CalculatorWebService.HelloWorldRequest inValue = new SOAPClient.CalculatorWebService.HelloWorldRequest();
            inValue.Body = new SOAPClient.CalculatorWebService.HelloWorldRequestBody();
            return ((SOAPClient.CalculatorWebService.CalculateSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPClient.CalculatorWebService.CalculationResponse SOAPClient.CalculatorWebService.CalculateSoap.Calculation(SOAPClient.CalculatorWebService.CalculationRequest request) {
            return base.Channel.Calculation(request);
        }
        
        public double Calculation(double x, double y, string operation) {
            SOAPClient.CalculatorWebService.CalculationRequest inValue = new SOAPClient.CalculatorWebService.CalculationRequest();
            inValue.Body = new SOAPClient.CalculatorWebService.CalculationRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            inValue.Body.operation = operation;
            SOAPClient.CalculatorWebService.CalculationResponse retVal = ((SOAPClient.CalculatorWebService.CalculateSoap)(this)).Calculation(inValue);
            return retVal.Body.CalculationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPClient.CalculatorWebService.CalculationResponse> SOAPClient.CalculatorWebService.CalculateSoap.CalculationAsync(SOAPClient.CalculatorWebService.CalculationRequest request) {
            return base.Channel.CalculationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPClient.CalculatorWebService.CalculationResponse> CalculationAsync(double x, double y, string operation) {
            SOAPClient.CalculatorWebService.CalculationRequest inValue = new SOAPClient.CalculatorWebService.CalculationRequest();
            inValue.Body = new SOAPClient.CalculatorWebService.CalculationRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            inValue.Body.operation = operation;
            return ((SOAPClient.CalculatorWebService.CalculateSoap)(this)).CalculationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPClient.CalculatorWebService.SayGoodByeResponse SOAPClient.CalculatorWebService.CalculateSoap.SayGoodBye(SOAPClient.CalculatorWebService.SayGoodByeRequest request) {
            return base.Channel.SayGoodBye(request);
        }
        
        public string SayGoodBye(string name) {
            SOAPClient.CalculatorWebService.SayGoodByeRequest inValue = new SOAPClient.CalculatorWebService.SayGoodByeRequest();
            inValue.Body = new SOAPClient.CalculatorWebService.SayGoodByeRequestBody();
            inValue.Body.name = name;
            SOAPClient.CalculatorWebService.SayGoodByeResponse retVal = ((SOAPClient.CalculatorWebService.CalculateSoap)(this)).SayGoodBye(inValue);
            return retVal.Body.SayGoodByeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPClient.CalculatorWebService.SayGoodByeResponse> SOAPClient.CalculatorWebService.CalculateSoap.SayGoodByeAsync(SOAPClient.CalculatorWebService.SayGoodByeRequest request) {
            return base.Channel.SayGoodByeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPClient.CalculatorWebService.SayGoodByeResponse> SayGoodByeAsync(string name) {
            SOAPClient.CalculatorWebService.SayGoodByeRequest inValue = new SOAPClient.CalculatorWebService.SayGoodByeRequest();
            inValue.Body = new SOAPClient.CalculatorWebService.SayGoodByeRequestBody();
            inValue.Body.name = name;
            return ((SOAPClient.CalculatorWebService.CalculateSoap)(this)).SayGoodByeAsync(inValue);
        }
    }
}
